# Generated by Django 5.0.6 on 2025-09-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_direct_question'),
        ('core', '0002_notification_question_question_auto_awarded'),
    ]

    operations = [
    ]
