# Generated by Django 5.0.6 on 2025-09-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20250909_1118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pointtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='directquestion',
            new_name='core_direct_sender__f53189_idx',
            old_name='core_dq_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='directquestion',
            new_name='core_direct_recipie_e0014e_idx',
            old_name='core_dq_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='directquestion',
            new_name='core_direct_created_17e76a_idx',
            old_name='core_dq_created_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='assigned_answerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-created_at'], name='core_answer_created_8b24ba_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='core_answer_questio_30e282_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['user', 'other', '-created_at'], name='core_chatlo_user_id_061934_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='core_notifi_user_id_cb8d84_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='core_pointt_user_id_7b31d9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='core_questi_created_e034c2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['urgent', '-created_at'], name='core_questi_urgent_ee8627_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='core_tag_name_102daa_idx'),
        ),
    ]
